name: Build

on: push

jobs:
  now:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [windows-2022, ubuntu-20.04]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run on Linux
        if: runner.os == 'Linux'
        run: |
          make
          tar -czf obfuscator.tar.gz -C src obfuscate -C obfuscator-src obfuscator.lua

      - name: Setup cygwin
        if: runner.os == 'Windows'
        uses: cygwin/cygwin-install-action@master

      - name: Run on Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          bash -c "make --version"
          bash -c "make"
          tar -czf obfuscator.tar.gz -C src obfuscate.exe -C obfuscator-src obfuscator.lua

      - name: Windows Release
        if: runner.os == 'Windows'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Windows
          make_latest: true
          files: |
            obfuscator.tar.gz

      - name: Linux Release
        if: runner.os == 'Linux'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Linux
          make_latest: true
          files: |
            obfuscator.tar.gz
